### ISSUE TITLE
Se muestran estrellas en el viejo formato

### ISSUE THREAD

**Issue by AxelRudz** [juliancasaburi/HomeSwitchHome#10]
En la vista de login, en la parte de subasta aleatoria, se muestran las estrellas en formato viejo, cuando en la propiedad aleatoria se muestran estrellas con el formato nuevo.

**Comment by juliancasaburi** [comment]
El mismo error sucede en la vista register

**Comment by juliancasaburi** [comment]
Sería buena idea refactorizar el código que muestra una propiedad/semana, para eliminar el código duplicado, que es propenso a errores como este.
Habría que moverlo a un partial y luego en las vistas hacer uso de la directive @include de Blade
https://laravel.com/docs/5.8/blade#including-sub-views
