### ISSUE TITLE
Problema con listado de reservas

### ISSUE THREAD

**Issue by AxelRudz** [juliancasaburi/HomeSwitchHome#12]
El listado de reservas no muestra el monto cuando un usuario premium se adjudica una semana.

**Comment by juliancasaburi** [comment]
Las reservas por modalidad "premium" tienen el valor null en la columna 'valor_reservado'

Cuando un usuario premium realiza una reserva por modalidad "Reserva Directa", sólo se le descuenta 1 crédito. No se le descuenta saldo.

Podría diferenciarse la celda "Monto".

https://github.com/juliancasaburi/HomeSwitchHome/blob/ee7e7250b16698853992faf9f0e0e7a0f86a1198/resources/views/user/user-reservation-list.blade.php#L87
