### ISSUE TITLE
Problema con requests

### ISSUE THREAD

**Issue by AxelRudz** [juliancasaburi/HomeSwitchHome#3]
Si se clickea mas de dos veces el boton submit, el programa no funciona correctamente debido a la cantidad de requests.

https://github.com/juliancasaburi/HomeSwitchHome/blob/b4320976ddc0095427d7146bcc9d6e9f87d7b4aa/resources/views/admin/admin-property-list.blade.php#L1-174

**Comment by juliancasaburi** [comment]
Al ser funcionalidad perteneciente a 'Administrador', la solución será únicamente client-side.
